#
# \brief  Baseband firewall on Linux
# \author Alexander Senier
# \date   2017-12-27
#

set build_components {
	core init
    app/linux_nic_raweth
    drivers/timer
	server/baseband_firewall
    server/linux_nic_raweth
}

set if_bp $::env(IF_BP)
set if_ap $::env(IF_AP)

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>
}

append_platform_drv_config

append config {

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
		<route>
			<any-service><parent/><any-child/></any-service>
		</route>
	</start>

	<start name="server-linux_nic_raweth">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nic"/></provides>
}

append config "<config interface=\"$if_bp\"/>"

append config {
		<route>
			<any-service><parent/><any-child/></any-service>
		</route>
	</start>

	<start name="baseband-fw">
		<resource name="RAM" quantum="16M"/>
		<provides><service name="Nic"/></provides>
		<config uplink="ap" downlink="bp"/>
		<route>
            <service name="Nic"><child name="server-linux_nic_raweth"/></service>
			<any-service><parent/><any-child/></any-service>
		</route>
	</start>

    <start name="client-linux_nic_raweth">
        <resource name="RAM" quantum="5M"/>
}

append config "<config interface=\"$if_ap\"/>"

append config {
        <route>
            <service name="Nic"><child name="baseband-fw"/></service>
            <any-service><parent/></any-service>
        </route>
    </start>

</config>
}

install_config $config

#
# Boot modules
#

# generic modules
set boot_modules {
    core init
    ld.lib.so
    timer
	baseband-fw
    server-linux_nic_raweth
    client-linux_nic_raweth
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

run_genode_until forever
