#
# \brief  Test linux raw Ethernet Nic server
# \author Alexander Senier
# \date   2017-12-27
#

set build_components {
	core init
    server/linux_nic_raweth
    test/nic_loopback
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>
}

append_platform_drv_config

append config {

	<start name="server-linux_nic_raweth" priority="-1">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nic"/></provides>
        <config interface="lo"/>
		<route>
			<any-service><parent/><any-child/></any-service>
		</route>
	</start>

    <start name="test-nic_loopback">
        <resource name="RAM" quantum="2M"/>
        <route>
            <service name="Nic"><child name="server-linux_nic_raweth"/></service>
            <any-service><parent/></any-service>
        </route>
    </start>

</config>
}

install_config $config

#
# Boot modules
#

# generic modules
set boot_modules {
    core init
    ld.lib.so
    server-linux_nic_raweth
    test-nic_loopback
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

run_genode_until forever
